package ar.ospim.empleadores.exception;

import lombok.Getter;

@Getter
public enum CommonEnumException {
	REGISTRO_INEXISTENTE,
	REGISTRO_INEXISTENTE_ID,
	REGISTRO_DUPLICADO,
	REGISTRO_BAJA,
	CODIGO_CON_FK,
	CODIGO_INVALIDO,
	CODIGO_INVALIDO_NOMBRE,
	ID_NO_INFORMADO,
	CODIGO_NO_INFORMADO,
	USUARIO_EMPRESA_DIFERENTE,
	EMPRESA_NO_INFORMADA,
	ATRIBUTO_OBLIGADO,
	PERIODO_FUTURO,
	FECHA_RANGO_EXISTENTE,
	FECHA_FMT_INVALIDO,
	FILTRO_OBLIGATORIO,
	ID_DIFIERE_DE_ATRIBUTO,
	MAIL_FORMATO,
	ERROR_FECHA_PASADA,
	IMPORTE_NEGATIVO,
	ATRIBUTO_MAYOR_A_CERO,
	ATRIBUTO_BIGDECIMAL,
	;
	
	public String getMsgKey() {
		return "comun.input." + this.name();
	}

}
